# Generated by Django 3.2.13 on 2022-06-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestParams',
            new_name='E2ETestParams',
        ),
        migrations.RenameModel(
            old_name='TestResults',
            new_name='E2ETestResults',
        ),
    ]
