# Generated by Django 3.2.13 on 2022-06-13 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 13, 20, 41, 49, 608901)),
        ),
    ]
