# Generated by Django 3.2.13 on 2022-06-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e2etestparams',
            old_name='launches_every_x_hours',
            new_name='launches_per_day',
        ),
    ]
