# Generated by Django 3.2.13 on 2022-06-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20220605_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlerTask',
            new_name='CrawlerResults',
        ),
    ]
