# Generated by Django 3.2.13 on 2022-06-14 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_e2etestparamsmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 12, 26, 4, 125206)),
        ),
    ]
