# Generated by Django 3.2.13 on 2022-06-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('core_app', '0002_rename_launches_every_x_hours_e2etestparams_launches_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2etestparams',
            name='celery_task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
    ]
