# Generated by Django 3.2.13 on 2022-07-10 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20220705_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='E2ETestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 'wait'), (2, 'click')], default=1)),
                ('wait_time_in_sec', models.IntegerField(max_length=3)),
                ('css_selector_click', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 14, 51, 18, 677403)),
        ),
    ]
