# Generated by Django 3.2.13 on 2022-07-11 12:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20220710_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='E2ETestActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 'wait'), (2, 'click')], default=1)),
                ('wait_time_in_sec', models.IntegerField(max_length=3)),
                ('css_selector_click', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='E2ETestEvent',
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 12, 49, 29, 956564)),
        ),
        migrations.AddField(
            model_name='e2etestactionmodel',
            name='e2e_test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.e2etestparamsmodel'),
        ),
    ]
