# Generated by Django 3.2.13 on 2022-06-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('core_app', '0005_alter_e2etestparams_celery_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestparams',
            name='celery_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
