# Generated by Django 3.2.13 on 2022-07-15 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20220712_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestactionmodel',
            name='css_selector_click',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='e2etestactionmodel',
            name='wait_time_in_sec',
            field=models.IntegerField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 15, 17, 12, 2, 146679)),
        ),
    ]
