# Generated by Django 3.2.13 on 2022-06-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_e2etestparams_celery_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e2etestparams',
            old_name='celery_task',
            new_name='periodic_task',
        ),
    ]
