# Generated by Django 3.2.13 on 2022-07-15 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_auto_20220715_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestactionmodel',
            name='wait_time_in_sec',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 15, 19, 33, 7, 688686)),
        ),
    ]
