# Generated by Django 3.2.13 on 2022-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_rename_celery_task_e2etestparams_periodic_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e2etestresults',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='e2etestparams',
            name='link',
        ),
        migrations.AddField(
            model_name='e2etestparams',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
