# Generated by Django 3.2.13 on 2022-06-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_e2etestparams_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestparams',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
