# Generated by Django 3.2.13 on 2022-07-21 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_auto_20220719_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e2etestactionmodel',
            old_name='css_selector_click',
            new_name='xpath_click',
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 15, 25, 33, 77533)),
        ),
    ]
