# Generated by Django 3.2.13 on 2022-07-22 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_auto_20220721_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2etestresultsmodel',
            name='error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 12, 27, 35, 148233)),
        ),
    ]
