# Generated by Django 3.2.13 on 2022-08-12 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_auto_20220722_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 12, 14, 57, 41, 599690)),
        ),
        migrations.AlterField(
            model_name='e2etestresultsmodel',
            name='failed_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
