# Generated by Django 3.2.13 on 2022-08-12 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_auto_20220812_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e2etestresultsmodel',
            old_name='failed_details',
            new_name='error_list',
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 12, 14, 59, 28, 363377)),
        ),
    ]
