# Generated by Django 3.2.13 on 2022-08-17 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_auto_20220816_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestactionmodel',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'wait'), (2, 'click')], default=0),
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 17, 10, 7, 26, 771544)),
        ),
    ]
