# Generated by Django 3.2.13 on 2022-08-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_auto_20220817_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e2etestactionmodel',
            name='event_type',
            field=models.IntegerField(blank=True, choices=[(1, 'wait'), (2, 'click')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='e2etestparamsmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 17, 10, 13, 7, 745701)),
        ),
    ]
